### ISSUE TITLE
Confused by `contains_exactly` message

### ISSUE THREAD

**Issue by danodonovan** [mwilliamson/python-precisely#3]
When asserting using `contains_exactly` I was a little confused by the error message. The fault was mine, I was passing the matcher a list rather than the elements of the list. However, the error message wasn't immediately clear to me - although I'm not sure the error should be clearer if the API usage was incorrect.

```
        assert_that(degrees, contains_exactly([
>           (1, 2), (2, 1), (3, 1), (4, 0)
        ]))

tests/build/test_importer.py:53:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

value = [(1, 2), (2, 1), (3, 1), (4, 0)], matcher = <precisely.iterable_matchers.ContainsExactlyMatcher object at 0x10f6635f8>

    def assert_that(value, matcher):
        result = matcher.match(value)
        if not result.is_match:
>           raise AssertionError("\nExpected: {0}\nbut: {1}".format(matcher.describe(), result.explanation))
E           AssertionError:
E           Expected: iterable containing in any order:
E             * [(1, 2), (2, 1), (3, 1), (4, 0)]
E           but: was missing element:
E             * [(1, 2), (2, 1), (3, 1), (4, 0)]
E           mismatched elements:
E             * (1, 2): was (1, 2)
E             * (2, 1): was (2, 1)
E             * (3, 1): was (3, 1)
E             * (4, 0): was (4, 0)
```

**Comment by mwilliamson** [comment]
Thanks for the report. I think there are two things we could do to make this clearer. The first would be to detect this specific case i.e. a list (or other iterable) is being passed into `contains_exactly` and show a hint in the assertion error. Having said that, we'd want to avoid showing the hint when the use-case is valid e.g. on a list of lists, so it's not clear how to avoid unhelpful hints.

The second confusing thing is more general: when we list mismatched elements, we list both element value, and the mismatch. However, if the elements are just being matched on equality, then the mismatch description doesn't add anything, and in fact makes things more confusing. So we could detect this case and not show the mismatch description if it's just going to reiterate the value. This would change the message to:

```
E           AssertionError:
E           Expected: iterable containing in any order:
E             * [(1, 2), (2, 1), (3, 1), (4, 0)]
E           but: was missing element:
E             * [(1, 2), (2, 1), (3, 1), (4, 0)]
E           mismatched elements:
E             * (1, 2)
E             * (2, 1)
E             * (3, 1)
E             * (4, 0)
```

The expectation could also be clarified to include the expected length:

```
E           AssertionError:
E           Expected: iterable containing these 1 element(s) in any order:
E             * [(1, 2), (2, 1), (3, 1), (4, 0)]
E           but: was missing element:
E             * [(1, 2), (2, 1), (3, 1), (4, 0)]
E           mismatched elements:
E             * (1, 2)
E             * (2, 1)
E             * (3, 1)
E             * (4, 0)
```

Any better?

**Comment by danodonovan** [comment]
Yes I think so. Thanks

**Comment by mwilliamson** [comment]
So far, I've changed the explanations so that your example would be:

```
Expected: iterable containing 1 element:
  * [(1, 2), (2, 1), (3, 1), (4, 0)]
but: was missing element:
  * [(1, 2), (2, 1), (3, 1), (4, 0)]
These elements were in the iterable, but did not match:
  * (1, 2): was (1, 2)
  * (2, 1): was (2, 1)
  * (3, 1): was (3, 1)
  * (4, 0): was (4, 0)
```

I've avoided removing the mismatch explanations, even when they're just a repetition of the repr of the element, since it could be confusing if some elements have the explanation and others don't. I was thinking of explicitly explaining that the suffix is the mismatch explanation, but I wonder if that would be overly verbose?

```
Expected: iterable containing 1 element:
  * [(1, 2), (2, 1), (3, 1), (4, 0)]
but: was missing element:
  * [(1, 2), (2, 1), (3, 1), (4, 0)]
These elements were in the iterable, but did not match:
  * (1, 2)
    * mismatch reason: was (1, 2)
  * (2, 1)
    * mismatch reason: was (2, 1)
  * (3, 1)
    * mismatch reason: was (3, 1)
  * (4, 0)
    * mismatch reason: was (4, 0)
```

**Comment by danodonovan** [comment]
Personally I find the top explanation clearer, so that would be my preference - although I can see the how later explanation might be more generic. Thank!

**Comment by mwilliamson** [comment]
I think this can be closed now, but feel free to disagree.
